# Generated by Django 4.2.4 on 2023-08-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0003_cake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='picture',
            field=models.ImageField(upload_to='https://s3.console.aws.amazon.com/s3/buckets/cake-products'),
        ),
    ]
