# Generated by Django 4.2.4 on 2023-08-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0005_alter_cake_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='picture',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='cake',
            name='flavor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
