# Generated by Django 4.2.4 on 2023-08-25 03:54

import MagnoliaCakesAndCupcakes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0007_rename_image_cake_picture_alter_cake_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='picture',
            field=models.ImageField(upload_to=MagnoliaCakesAndCupcakes.models.upload_to),
        ),
    ]
