# Generated by Django 4.2.4 on 2023-09-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0008_alter_cake_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('answer', models.TextField()),
                ('categories', models.ManyToManyField(to='MagnoliaCakesAndCupcakes.faqcategories')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
    ]
