# Generated by Django 4.2.4 on 2023-09-14 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0009_faqcategories_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQCategories',
            new_name='FAQCategory',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
