# Generated by Django 4.2.4 on 2023-09-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0010_rename_faqcategories_faqcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='categories',
            new_name='category',
        ),
    ]
