# Generated by Django 4.2.4 on 2023-09-18 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0009_aboutus'),
        ('MagnoliaCakesAndCupcakes', '0011_rename_categories_question_category'),
    ]

    operations = [
    ]
