# Generated by Django 4.2.4 on 2023-09-19 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0012_merge_20230918_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsandconditions',
            name='content',
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=150)),
                ('policy_content', models.TextField()),
                ('terms_and_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MagnoliaCakesAndCupcakes.termsandconditions')),
            ],
        ),
    ]
