# Generated by Django 4.2.4 on 2023-09-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0012_merge_20230918_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_hrs_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_heading', models.CharField(max_length=150)),
                ('contact_us_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_heading', models.CharField(max_length=150)),
                ('location_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_heading', models.CharField(max_length=150)),
                ('social_media_platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=300)),
                ('account_name', models.CharField(max_length=150)),
                ('account_link', models.TextField()),
            ],
        ),
    ]
