# Generated by Django 4.2.4 on 2023-09-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0012_merge_20230918_1111'),
        ('MagnoliaCakesAndCupcakes', '0013_flavoursandservingsinfo'),
    ]

    operations = [
    ]
