# Generated by Django 4.2.4 on 2023-09-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0014_termsandcondition_delete_policy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsandcondition',
            options={'ordering': ['policy_name']},
        ),
    ]
