# Generated by Django 4.2.4 on 2023-09-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0014_merge_20230919_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavoursandservings',
            options={'verbose_name_plural': 'Flavours and Servings Lists'},
        ),
        migrations.AlterModelOptions(
            name='flavoursandservingsinfo',
            options={'verbose_name_plural': 'Flavours and Servings Info'},
        ),
    ]
