# Generated by Django 4.2.4 on 2023-09-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0014_alter_footerbusinesshours_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedias',
            options={'ordering': ['social_media_platform'], 'verbose_name_plural': 'Social Medias'},
        ),
    ]
