# Generated by Django 4.2.4 on 2023-09-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0015_alter_flavoursandservings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavoursandservings',
            options={'ordering': ['title'], 'verbose_name_plural': 'Flavours and Servings Lists'},
        ),
    ]
