# Generated by Django 4.2.4 on 2023-09-20 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0015_alter_termsandcondition_options'),
        ('MagnoliaCakesAndCupcakes', '0016_alter_flavoursandservings_options'),
    ]

    operations = [
    ]
