# Generated by Django 4.2.4 on 2023-09-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0015_alter_socialmedias_options'),
        ('MagnoliaCakesAndCupcakes', '0017_merge_20230920_0057'),
    ]

    operations = [
    ]
