# Generated by Django 4.2.4 on 2023-09-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0017_merge_20230920_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_email', models.CharField(default='kimt12531@gmail.com', help_text='This will be the email that receives Contact Us and Get A Quote submissions.', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Contact Us Email',
            },
        ),
    ]
