# Generated by Django 4.2.4 on 2023-09-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0018_gallerycategory_alter_cake_name_galleryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='category',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='categories',
            field=models.ManyToManyField(to='MagnoliaCakesAndCupcakes.gallerycategory'),
        ),
    ]
