# Generated by Django 4.2.4 on 2023-09-22 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0018_merge_20230922_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavoursandservingsinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='socialmedias',
            options={'verbose_name_plural': 'Flavours and Servings Info'},
        ),
    ]
