# Generated by Django 4.2.4 on 2023-09-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0020_alter_flavoursandservingsinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_heading', models.CharField(max_length=200)),
                ('location_info', models.TextField()),
                ('business_hours_heading', models.CharField(max_length=200)),
                ('business_hours_info', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Location Page Content',
            },
        ),
    ]
