# Generated by Django 4.2.4 on 2023-09-22 05:11

import MagnoliaCakesAndCupcakes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0021_locationpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=MagnoliaCakesAndCupcakes.models.upload_to)),
            ],
        ),
    ]
