# Generated by Django 4.2.4 on 2023-09-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0018_contactusemail'),
        ('MagnoliaCakesAndCupcakes', '0023_alter_sliderimage_image'),
    ]

    operations = [
    ]
