# Generated by Django 4.2.4 on 2023-09-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0019_remove_galleryitem_category_galleryitem_categories'),
        ('MagnoliaCakesAndCupcakes', '0024_merge_20230923_0430'),
    ]

    operations = [
    ]
