# Generated by Django 4.2.4 on 2023-09-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0024_merge_20230923_0430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['title'], 'verbose_name_plural': 'FAQ Categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question'], 'verbose_name_plural': 'FAQ Questions'},
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name_plural': 'Slider Images'},
        ),
        migrations.AddField(
            model_name='flavoursandservings',
            name='type',
            field=models.CharField(choices=[('flavours', 'flavours'), ('fillings', 'fillings')], default='flavours', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactusemail',
            name='your_email',
            field=models.CharField(help_text='This will be the email that receives Contact Us and Get A Quote submissions.', max_length=200),
        ),
    ]
