# Generated by Django 4.2.4 on 2023-09-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0026_rename_gallerycategory_cakecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='description',
        ),
        migrations.AddField(
            model_name='cake',
            name='categories',
            field=models.ManyToManyField(to='MagnoliaCakesAndCupcakes.cakecategory'),
        ),
    ]
