# Generated by Django 4.2.4 on 2023-09-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0026_backupemail'),
        ('MagnoliaCakesAndCupcakes', '0026_video_alter_contactusemail_your_email'),
        ('MagnoliaCakesAndCupcakes', '0027_remove_cake_description_cake_categories'),
    ]

    operations = [
    ]
