# Generated by Django 4.2.4 on 2023-09-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0027_homepagewelcomesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageAboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('paragraph', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Homepage About Us Section',
            },
        ),
    ]
