# Generated by Django 4.2.4 on 2023-09-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0028_homepageaboutussection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us Page'},
        ),
    ]
