# Generated by Django 4.2.4 on 2023-09-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0028_merge_20230928_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
