# Generated by Django 4.2.4 on 2023-09-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0029_alter_aboutus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageaboutussection',
            name='heading',
            field=models.CharField(default='About Us', max_length=300),
        ),
    ]
