# Generated by Django 4.2.4 on 2023-09-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0029_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavoursandservings',
            name='type',
            field=models.CharField(choices=[('Flavours', 'Flavours'), ('Fillings', 'Fillings')], default='flavours', max_length=100),
        ),
    ]
