# Generated by Django 4.2.4 on 2023-09-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0030_alter_homepageaboutussection_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageGallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Our Collection', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Homepage Gallery Section',
            },
        ),
    ]
