# Generated by Django 4.2.4 on 2023-09-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0027_remove_cake_description_cake_categories'),
        ('MagnoliaCakesAndCupcakes', '0031_homepagegallerysection'),
    ]

    operations = [
    ]
