# Generated by Django 4.2.4 on 2023-09-28 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MagnoliaCakesAndCupcakes', '0031_alter_userprofile_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserVideo',
        ),
    ]
