# Generated by Django 4.2.4 on 2023-09-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0032_alter_quote_options_rename_fillings_quote_filling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='servings_or_amount',
            field=models.IntegerField(default=0),
        ),
    ]
