# Generated by Django 4.2.4 on 2023-09-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0026_video_alter_contactusemail_your_email'),
        ('MagnoliaCakesAndCupcakes', '0032_merge_20230927_0828'),
    ]

    operations = [
    ]
