# Generated by Django 4.2.4 on 2023-10-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0032_rename_userprofile_uservideo'),
        ('MagnoliaCakesAndCupcakes', '0033_merge_20230928_0710'),
    ]

    operations = [
    ]
