# Generated by Django 4.2.4 on 2023-10-01 23:47

import MagnoliaCakesAndCupcakes.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0033_merge_20230928_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakecategory',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=MagnoliaCakesAndCupcakes.models.GalleryCategory.upload_to__gallery_category_cover),
            preserve_default=False,
        ),
    ]
