# Generated by Django 4.2.4 on 2023-10-06 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0034_merge_20231002_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagewelcomesection',
            name='quote',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
