# Generated by Django 4.2.4 on 2023-10-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0034_merge_20231002_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount_off', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_off', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True)),
                ('redeem_by', models.DateTimeField(blank=True, null=True)),
                ('stripe_coupon_id', models.CharField(blank=True, editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StripePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('stripe_promotion_id', models.CharField(blank=True, editable=False, max_length=100)),
            ],
        ),
    ]
