# Generated by Django 4.2.4 on 2023-10-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0034_cakecategory_picture'),
        ('MagnoliaCakesAndCupcakes', '0034_merge_20231002_2258'),
    ]

    operations = [
    ]
