# Generated by Django 4.2.4 on 2023-10-06 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0033_alter_quote_servings_or_amount'),
        ('MagnoliaCakesAndCupcakes', '0034_merge_20231002_2258'),
    ]

    operations = [
    ]
