# Generated by Django 4.2.4 on 2023-10-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0035_merge_20231006_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us Page'},
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_of_event',
            field=models.CharField(max_length=10),
        ),
    ]
