# Generated by Django 4.2.4 on 2023-10-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0035_stripecoupon_stripepromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecoupon',
            name='amount_off',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stripecoupon',
            name='percent_off',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
