# Generated by Django 4.2.4 on 2023-10-06 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0035_homepagewelcomesection_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='about_us_page/'),
            preserve_default=False,
        ),
    ]
