# Generated by Django 4.2.4 on 2023-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0036_alter_stripecoupon_amount_off_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripecoupon',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='stripecoupon',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stripepromotion',
            name='id',
        ),
        migrations.AlterField(
            model_name='stripecoupon',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stripepromotion',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
