# Generated by Django 4.2.4 on 2023-10-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0036_alter_aboutus_options_alter_quote_date_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date_of_event',
            field=models.DateField(),
        ),
    ]
