# Generated by Django 4.2.4 on 2023-10-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0035_merge_20231003_0007'),
        ('MagnoliaCakesAndCupcakes', '0037_alter_quote_date_of_event'),
    ]

    operations = [
    ]
