# Generated by Django 4.2.4 on 2023-10-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0037_alter_stripecoupon_options_remove_stripecoupon_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepromotion',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MagnoliaCakesAndCupcakes.stripecoupon'),
        ),
    ]
