# Generated by Django 4.2.4 on 2023-10-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0035_quoterequest'),
        ('MagnoliaCakesAndCupcakes', '0038_merge_20231006_2339'),
        ('MagnoliaCakesAndCupcakes', '0038_merge_20231007_1625'),
    ]

    operations = [
    ]
