# Generated by Django 4.2.4 on 2023-10-06 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0038_alter_stripepromotion_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripepromotion',
            options={'ordering': ['code']},
        ),
    ]
