# Generated by Django 4.2.4 on 2023-10-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0039_merge_20231009_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuoteRequest',
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='filling',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='flavour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='product_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='serves',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='servings_or_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='videos',
            field=models.ManyToManyField(blank=True, to='MagnoliaCakesAndCupcakes.video'),
        ),
    ]
