# Generated by Django 4.2.4 on 2023-10-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0039_alter_stripepromotion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepromotion',
            name='description',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='stripepromotion',
            name='is_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
