# Generated by Django 4.2.4 on 2023-10-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0040_stripepromotion_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepromotion',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
