# Generated by Django 4.2.4 on 2023-10-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0046_userfirstorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepromotion',
            name='onlyFirstPurchaseOfUser',
            field=models.BooleanField(default=False),
        ),
    ]
