# Generated by Django 4.2.4 on 2023-10-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0036_aboutus_picture'),
        ('MagnoliaCakesAndCupcakes', '0037_alter_quote_date_of_event'),
        ('MagnoliaCakesAndCupcakes', '0048_rename_onlyfirstpurchaseofuser_stripepromotion_only_first_purchase_of_user_and_more'),
    ]

    operations = [
    ]
