# Generated by Django 4.2.4 on 2023-10-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0048_rename_onlyfirstpurchaseofuser_stripepromotion_only_first_purchase_of_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='FAQQuestion',
        ),
        migrations.AlterModelOptions(
            name='cakecategory',
            options={'verbose_name_plural': 'Cake Categories'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name_plural': 'FAQ Categories'},
        ),
        migrations.AlterModelOptions(
            name='faqquestion',
            options={'verbose_name_plural': 'FAQ Questions'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name_plural': 'Slider Images'},
        ),
        migrations.AlterModelOptions(
            name='stripecoupon',
            options={'ordering': ['name'], 'verbose_name_plural': 'Stripe Coupons'},
        ),
        migrations.AlterModelOptions(
            name='stripepromotion',
            options={'ordering': ['code'], 'verbose_name_plural': 'Stripe Promotions'},
        ),
        migrations.AlterModelOptions(
            name='termsandcondition',
            options={'ordering': ['policy_name'], 'verbose_name_plural': 'Terms And Conditions'},
        ),
        migrations.AlterModelOptions(
            name='userfirstorder',
            options={'ordering': ['user'], 'verbose_name_plural': 'User First Orders'},
        ),
        migrations.AlterModelOptions(
            name='uservideo',
            options={'ordering': ['user'], 'verbose_name_plural': 'User Videos'},
        ),
    ]
