# Generated by Django 4.2.4 on 2023-10-09 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0049_rename_question_faqquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepromotion',
            name='code',
            field=models.CharField(blank=True, help_text='You cannot change this field after creating the promotion.', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stripepromotion',
            name='coupon',
            field=models.ForeignKey(help_text='You cannot change this field after creating the promotion.', on_delete=django.db.models.deletion.CASCADE, to='MagnoliaCakesAndCupcakes.stripecoupon'),
        ),
    ]
