# Generated by Django 4.2.4 on 2023-10-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0049_merge_20231009_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cakecategory',
            options={'verbose_name_plural': 'Cake Categories'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name_plural': 'FAQ Categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'FAQ Questions'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.AlterModelOptions(
            name='stripecoupon',
            options={'ordering': ['name'], 'verbose_name_plural': 'Stripe Coupons'},
        ),
        migrations.AlterModelOptions(
            name='stripepromotion',
            options={'ordering': ['code'], 'verbose_name_plural': 'Stripe Promotions'},
        ),
        migrations.AlterModelOptions(
            name='termsandcondition',
            options={'ordering': ['policy_name'], 'verbose_name_plural': 'Terms And Conditions'},
        ),
        migrations.AlterModelOptions(
            name='userfirstorder',
            options={'ordering': ['user'], 'verbose_name_plural': 'User First Orders'},
        ),
        migrations.AlterModelOptions(
            name='uservideo',
            options={'ordering': ['user'], 'verbose_name_plural': 'User Videos'},
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='filling',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='flavour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='product_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='serves',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='servings_or_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stripecoupon',
            name='amount_off',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='You cannot change this field after creating the Coupon.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stripecoupon',
            name='max_redemptions',
            field=models.PositiveIntegerField(blank=True, help_text='You cannot change this field after creating the Coupon.', null=True),
        ),
        migrations.AlterField(
            model_name='stripecoupon',
            name='percent_off',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='You cannot change this field after creating the Coupon.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stripecoupon',
            name='redeem_by',
            field=models.DateTimeField(blank=True, help_text='You cannot change this field after creating the Coupon.', null=True),
        ),
        migrations.AlterField(
            model_name='stripepromotion',
            name='code',
            field=models.CharField(blank=True, help_text='You cannot change this field after creating the promotion.', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stripepromotion',
            name='coupon',
            field=models.ForeignKey(help_text='You cannot change this field after creating the promotion.', on_delete=django.db.models.deletion.CASCADE, to='MagnoliaCakesAndCupcakes.stripecoupon'),
        ),
    ]
