# Generated by Django 4.2.4 on 2023-10-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0050_alter_stripepromotion_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecoupon',
            name='amount_off',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='You cannot change this field after creating the Coupon.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stripecoupon',
            name='max_redemptions',
            field=models.PositiveIntegerField(blank=True, help_text='You cannot change this field after creating the Coupon.', null=True),
        ),
        migrations.AlterField(
            model_name='stripecoupon',
            name='percent_off',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='You cannot change this field after creating the Coupon.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stripecoupon',
            name='redeem_by',
            field=models.DateTimeField(blank=True, help_text='You cannot change this field after creating the Coupon.', null=True),
        ),
    ]
