# Generated by Django 4.2.4 on 2023-10-10 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0050_rename_question_faqquestion_and_more'),
    ]

    operations = [
        migrations.RunPython(lambda x, y: None, lambda x, y: None),
    ]
