# Generated by Django 4.2.4 on 2023-10-10 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0052_faqquestion_alter_faqcategory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
