# Generated by Django 4.2.4 on 2023-10-11 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0040_delete_quoterequest_alter_quote_date_of_event_and_more'),
        ('MagnoliaCakesAndCupcakes', '0053_delete_question'),
    ]

    operations = [
    ]
