# Generated by Django 4.2.4 on 2023-10-11 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MagnoliaCakesAndCupcakes', '0054_merge_20231011_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_submitted', models.DateTimeField(auto_now=True)),
                ('cakes', models.ManyToManyField(blank=True, to='MagnoliaCakesAndCupcakes.cake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, to='MagnoliaCakesAndCupcakes.video')),
            ],
            options={
                'verbose_name_plural': 'User Purchases',
                'ordering': ['time_submitted'],
            },
        ),
    ]
