# Generated by Django 4.2.4 on 2023-10-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0055_userpurchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpurchase',
            options={'ordering': ['-time_submitted'], 'verbose_name_plural': 'User Purchases'},
        ),
    ]
