# Generated by Django 4.2.4 on 2023-10-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0057_cake_active_cake_description_cake_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='price_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
