# Generated by Django 4.2.4 on 2023-10-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0058_cake_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='price_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='product_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
