# Generated by Django 4.2.4 on 2023-10-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0059_video_active_video_price_id_video_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='price',
        ),
        migrations.AddField(
            model_name='cake',
            name='product_type',
            field=models.CharField(choices=[('cake', 'Cake'), ('cupcake', 'Cupcake')], default='cake', max_length=10),
        ),
        migrations.CreateModel(
            name='CakeSizePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_prices', to='MagnoliaCakesAndCupcakes.cake')),
            ],
        ),
    ]
