# Generated by Django 4.2.4 on 2023-10-14 00:45

import MagnoliaCakesAndCupcakes.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0059_video_active_video_price_id_video_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagewelcomesection',
            options={'verbose_name_plural': 'Homepage Top & Welcome Section'},
        ),
        migrations.AddField(
            model_name='homepagewelcomesection',
            name='banner',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=MagnoliaCakesAndCupcakes.models.HomepageWelcomeSection.upload_to_banner),
            preserve_default=False,
        ),
    ]
