# Generated by Django 4.2.4 on 2023-10-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0062_alter_cake_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakesizeprice',
            name='cake',
            field=models.ForeignKey(limit_choices_to={'product_type': 'cake'}, on_delete=django.db.models.deletion.CASCADE, related_name='size_prices', to='MagnoliaCakesAndCupcakes.cake'),
        ),
    ]
