# Generated by Django 4.2.4 on 2023-10-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0066_cakesizeprice_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CakeSizePrice',
            new_name='Cake',
        ),
    ]
