# Generated by Django 4.2.4 on 2023-10-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0069_cake_price_id_cake_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cake',
            new_name='CakeVariant',
        ),
    ]
