# Generated by Django 4.2.4 on 2023-10-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0071_merge_20231018_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cake',
            new_name='CakeVariant',
        ),
        migrations.RenameModel(
            old_name='CakeCategory',
            new_name='GalleryCategory',
        ),
    ]
