# Generated by Django 4.2.4 on 2023-10-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0071_rename_cake_cakevariant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CakeCategory',
            new_name='GalleryCategory',
        ),
    ]
