# Generated by Django 4.2.4 on 2023-10-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0072_rename_cakecategory_gallerycategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name_plural': 'Gallery Categories'},
        ),
    ]
