# Generated by Django 4.2.4 on 2023-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0072_rename_cakecategory_gallerycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='gallery/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name_plural': 'Gallery Categories'},
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='image',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='images',
            field=models.ManyToManyField(to='MagnoliaCakesAndCupcakes.file'),
        ),
    ]
