# Generated by Django 4.2.4 on 2023-10-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0073_alter_gallerycategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Gallery Items'},
        ),
    ]
