# Generated by Django 4.2.4 on 2023-10-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0073_file_alter_gallerycategory_options_and_more'),
        ('MagnoliaCakesAndCupcakes', '0074_alter_galleryitem_options'),
    ]

    operations = [
    ]
