# Generated by Django 4.2.4 on 2023-10-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0075_merge_20231018_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='images',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(default='', upload_to='gallery/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
