# Generated by Django 4.2.4 on 2023-10-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0073_alter_userpurchase_options_remove_userpurchase_cakes_and_more'),
        ('MagnoliaCakesAndCupcakes', '0076_remove_galleryitem_images_galleryitem_image_and_more'),
    ]

    operations = [
    ]
