# Generated by Django 4.2.4 on 2023-10-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0077_merge_20231019_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor',
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('product_type', models.CharField(choices=[('Cake', 'Cake'), ('Cupcake', 'Cupcake')], default='Cake', max_length=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='MagnoliaCakesAndCupcakes.product')),
            ],
        ),
        migrations.AlterField(
            model_name='cakevariant',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_prices', to='MagnoliaCakesAndCupcakes.flavor'),
        ),
    ]
