# Generated by Django 4.2.4 on 2023-10-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0077_merge_20231019_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'verbose_name_plural': 'Gallery Items'},
        ),
    ]
