# Generated by Django 4.2.4 on 2023-10-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0060_alter_homepagewelcomesection_options_and_more'),
        ('MagnoliaCakesAndCupcakes', '0078_alter_galleryitem_options'),
    ]

    operations = [
    ]
