# Generated by Django 4.2.4 on 2023-10-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0080_alter_gallerycategory_options_remove_product_flavor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='product_type',
        ),
    ]
