# Generated by Django 4.2.4 on 2023-10-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0081_remove_flavor_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
