# Generated by Django 4.2.4 on 2023-10-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0082_alter_flavor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='product_type',
            field=models.CharField(choices=[('Cake', 'Cake'), ('Cupcake', 'Cupcake')], default='Cake', editable=False, max_length=10),
        ),
    ]
