# Generated by Django 4.2.4 on 2023-10-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0083_flavor_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakevariant',
            name='cake',
            field=models.ForeignKey(limit_choices_to={'product_type': 'Cake'}, on_delete=django.db.models.deletion.CASCADE, related_name='size_prices', to='MagnoliaCakesAndCupcakes.flavor'),
        ),
    ]
