# Generated by Django 4.2.4 on 2023-10-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0084_alter_cakevariant_cake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
