# Generated by Django 4.2.4 on 2023-10-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0086_product_price_id_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flavor',
            old_name='product',
            new_name='product_item',
        ),
        migrations.RemoveField(
            model_name='cakevariant',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='cakevariant',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='flavor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flavor',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flavor',
            name='price_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='flavor',
            name='product_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
