# Generated by Django 4.2.4 on 2023-10-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0089_cakevariant_product_id_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakevariant',
            name='price_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='cakevariant',
            name='product_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
