# Generated by Django 4.2.4 on 2023-10-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0093_alter_userproductpurchase_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakevariant',
            name='product_name',
            field=models.CharField(default='test', editable=False),
            preserve_default=False,
        ),
    ]
