# Generated by Django 4.2.4 on 2023-10-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0080_stripepromotion_minimum_amount_and_more'),
        ('MagnoliaCakesAndCupcakes', '0094_cakevariant_product_name'),
    ]

    operations = [
    ]
