# Generated by Django 4.2.4 on 2024-05-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0095_merge_20231021_2356'),
        ('MagnoliaCakesAndCupcakes', '0095_merge_20231022_0002'),
    ]

    operations = [
    ]
