# Generated by Django 4.2.4 on 2023-10-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0096_merge_20231024_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServingsGuideInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServingsOfRoundCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_inches', models.IntegerField()),
                ('standard_serves', models.IntegerField()),
                ('coffee_serves', models.IntegerField()),
            ],
            options={
                'ordering': ['size_in_inches', 'standard_serves', 'coffee_serves'],
            },
        ),
        migrations.CreateModel(
            name='ServingsOfSquareCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_inches', models.IntegerField()),
                ('standard_serves', models.IntegerField()),
                ('coffee_serves', models.IntegerField()),
            ],
            options={
                'ordering': ['size_in_inches', 'standard_serves', 'coffee_serves'],
            },
        ),
    ]
