# Generated by Django 4.2.4 on 2023-10-23 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0097_servingsguideinfo_servingsofroundcake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servingsguideinfo',
            name='heading',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
