# Generated by Django 4.2.4 on 2023-10-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0098_servingsguideinfo_heading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servingsguideinfo',
            options={'verbose_name_plural': 'Servings Guide Info'},
        ),
        migrations.AlterModelOptions(
            name='servingsofroundcake',
            options={'verbose_name_plural': 'Servings Of Round Cakes'},
        ),
        migrations.AlterModelOptions(
            name='servingsofsquarecake',
            options={'verbose_name_plural': 'Servings Of Square Cakes'},
        ),
        migrations.AlterField(
            model_name='flavoursandservingsinfo',
            name='extra_points',
            field=models.TextField(blank=True),
        ),
    ]
