# Generated by Django 4.2.4 on 2023-10-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0062_usercustomerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustomerid',
            old_name='customer_ID',
            new_name='customer_id',
        ),
    ]
