# Generated by Django 4.2.4 on 2023-10-17 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MagnoliaCakesAndCupcakes', '0065_delete_userpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCakePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MagnoliaCakesAndCupcakes.cake')),
            ],
        ),
        migrations.CreateModel(
            name='UserPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_submitted', models.DateTimeField(auto_now=True)),
                ('cakes', models.ManyToManyField(blank=True, through='MagnoliaCakesAndCupcakes.UserCakePurchase', to='MagnoliaCakesAndCupcakes.cake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Purchases',
                'ordering': ['-time_submitted'],
            },
        ),
        migrations.CreateModel(
            name='UserVideoPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MagnoliaCakesAndCupcakes.userpurchase')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MagnoliaCakesAndCupcakes.video')),
            ],
        ),
        migrations.AddField(
            model_name='userpurchase',
            name='videos',
            field=models.ManyToManyField(blank=True, through='MagnoliaCakesAndCupcakes.UserVideoPurchase', to='MagnoliaCakesAndCupcakes.video'),
        ),
        migrations.AddField(
            model_name='usercakepurchase',
            name='user_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MagnoliaCakesAndCupcakes.userpurchase'),
        ),
    ]
