# Generated by Django 4.2.4 on 2023-10-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0060_stripepromotion_minimum_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepromotion',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='You cannot change this field after creating the Coupon.', max_digits=5),
        ),
    ]
