# Generated by Django 4.2.4 on 2023-10-17 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MagnoliaCakesAndCupcakes', '0061_alter_stripepromotion_minimum_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomerID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.CharField(blank=True, editable=False, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stripe Customer ID',
                'ordering': ['user'],
            },
        ),
    ]
