# Generated by Django 4.2.4 on 2023-10-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0064_alter_userpurchase_cakes_alter_userpurchase_videos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPurchase',
        ),
    ]
