# Generated by Django 4.2.4 on 2023-10-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0059_video_active_video_price_id_video_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepromotion',
            name='minimum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='You cannot change this field after creating the Coupon.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stripepromotion',
            name='only_first_purchase_of_user',
            field=models.BooleanField(default=False, help_text='You cannot change this field after creating the promotion.'),
        ),
    ]
