# Generated by Django 4.2.4 on 2023-10-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0066_usercakepurchase_userpurchase_uservideopurchase_and_more'),
        ('MagnoliaCakesAndCupcakes', '0070_merge_20231018_1447'),
    ]

    operations = [
    ]
