# Generated by Django 4.2.4 on 2023-10-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0060_alter_homepagewelcomesection_options_and_more'),
        ('MagnoliaCakesAndCupcakes', '0069_cake_price_id_cake_product_id'),
    ]

    operations = [
    ]
